2017-08-20 12:09:02  [ main:85 ] - [ ERROR ]  Fallback error:java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2b05039f rejected from java.util.concurrent.ThreadPoolExecutor@61e717c2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2017-08-20 12:09:45  [ main:82 ] - [ ERROR ]  Fallback error:java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2b05039f rejected from java.util.concurrent.ThreadPoolExecutor@61e717c2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2017-08-20 12:11:04  [ main:77 ] - [ ERROR ]  Fallback error:java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2b05039f rejected from java.util.concurrent.ThreadPoolExecutor@61e717c2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2017-08-20 12:11:28  [ main:87 ] - [ ERROR ]  Fallback error:java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2b05039f rejected from java.util.concurrent.ThreadPoolExecutor@61e717c2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2017-08-20 12:28:27  [ main:93 ] - [ ERROR ]  Fallback error:java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2b05039f rejected from java.util.concurrent.ThreadPoolExecutor@61e717c2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2017-08-20 12:30:19  [ main:80 ] - [ ERROR ]  Fallback error:java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2b05039f rejected from java.util.concurrent.ThreadPoolExecutor@61e717c2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2017-08-20 12:32:18  [ main:85 ] - [ ERROR ]  Fallback error:java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2b05039f rejected from java.util.concurrent.ThreadPoolExecutor@61e717c2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2017-08-20 12:34:29  [ main:86 ] - [ ERROR ]  Fallback error:java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2b05039f rejected from java.util.concurrent.ThreadPoolExecutor@61e717c2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2017-08-20 12:35:30  [ main:83 ] - [ ERROR ]  Fallback error:java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2b05039f rejected from java.util.concurrent.ThreadPoolExecutor@61e4705b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2017-08-20 12:36:02  [ main:76 ] - [ ERROR ]  Fallback error:java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2b05039f rejected from java.util.concurrent.ThreadPoolExecutor@61e4705b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2017-08-20 12:41:28  [ main:101 ] - [ ERROR ]  Fallback error:java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@2b05039f rejected from java.util.concurrent.ThreadPoolExecutor@61e4705b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
